name: photo_collage_creator
description: "Photo Collage Creator For Androids"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.0.7
  filesystem_picker: ^4.1.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_page_stepper: ^0.0.1
  multiselect: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/heart.png
    - assets/heptagon.png
    - assets/hexagon.png
    - assets/pentagon.png
    - assets/triangle.png
